# Generated by Django 3.1.1 on 2020-10-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destinationlux'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DestinationLux',
        ),
    ]
